### PR TITLE
Don't warn about renamed imports.

### LINKED ISSUE #310: Don't warn about renamed local imports
The local import check incorrectly warns about this:

```D
void foo() {
  import stdio = std.stdio;
}
```

The problem with a bare local import is that it can shadow an open-ended set of declarations. Selective imports fix that, and that's what Dscanner recommends. Renamed imports also fix that, but Dscanner doesn't realize that.

### PR DESCRIPTION
**Pull request by dhasenan**
Renamed imports can't shadow an arbitrarily large set of declarations, so don't warn about them.

Fixes #310.

### CODE REVIEW

File: src/analysis/local_imports.d [hunk 1]
```diff
@@ -75,3 +81,21 @@ private:
...
+	import analysis.config : StaticAnalysisConfig;
+
+	StaticAnalysisConfig sac;
+	sac.local_import_check = true;
+	assertAnalyzerWarnings(q{
+		void testLocalImport()
+		{
+			import std.stdio; // [warn]: Local imports should specify the symbols being imported to avoid hiding local symbols.
+			import std.fish : scales, head;
+			import DAGRON = std.experimental.dragon;
```
Comment (Hackerpilot) [inline src/analysis/local_imports.d]: Strong Mad? You just keep doing your thing, man.
